services:
  - type: web
    name: car-match-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
