name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main, prod, stage ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          # Set your deployed backend URL here, e.g., from repo variables/secrets
          REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
          REACT_APP_USE_REAL_EVENTS: ${{ vars.REACT_APP_USE_REAL_EVENTS }}
        run: npm run build

      - name: Check backend health (warn only)
        if: ${{ vars.REACT_APP_API_BASE_URL != '' }}
        run: |
          API="${{ vars.REACT_APP_API_BASE_URL }}"
          echo "Pinging $API/healthz"
          RESP=$(curl -sS -m 10 "$API/healthz" || true)
          echo "::notice::/healthz response: $RESP"
          if ! echo "$RESP" | grep -q '"connected":true'; then
            echo "::warning::Backend /healthz did not report connected=true. Proceeding with deploy."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build
