name: Snyk Security Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Ensure SNYK_TOKEN is available
        run: |
          if [ -z "$SNYK_TOKEN" ]; then
            echo "SNYK_TOKEN secret is not configured." >&2
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Snyk test (backend)
        run: npx snyk test --severity-threshold=medium
        working-directory: backend

      - name: Snyk monitor (backend)
        run: npx snyk monitor --severity-threshold=medium --project-name=car-match-backend
        working-directory: backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Snyk test (frontend)
        run: npx snyk test --severity-threshold=medium
        working-directory: frontend

      - name: Snyk monitor (frontend)
        run: npx snyk monitor --severity-threshold=medium --project-name=car-match-frontend
        working-directory: frontend
